### ISSUE TITLE
300 USD Create API Endpoint and Configure Vercel

### ISSUE THREAD

**Issue by esteblock** [soroswap/zephyr-programs#25]
Currently our frontend needs an API to get info from Mercury Zephyr
https://github.com/soroswap/frontend/blob/85e531a4b449cb50e3b374dd19c76d9d6bda80ef/src/services/pairs.ts#L20
https://github.com/soroswap/frontend/blob/85e531a4b449cb50e3b374dd19c76d9d6bda80ef/src/services/pairs.ts#L32

This API is currently provided by the info project.
This is because before the only protocols that we wanted to use was only Soroswap.
However now we want to use several protocols (Soroswap, Phoenix, Aqua)

So we created a new endpoint in info for Phoenix
https://github.com/soroswap/info/blob/main/pages/api/pairs/phoenix.tsx

So the current situation is
- The info repos is now also an API. We dont want this
- The info repo calls itself. We dont want this
- The frontend repo calls the info API. This is strage

**What we want**
We want that the zephyr-program repo handles the API.

So we need to create endpoints similar as
https://github.com/soroswap/info/blob/main/pages/api/pairs/phoenix.tsx
https://github.com/soroswap/info/blob/main/pages/api/pairs/plain.tsx

in order to get tjhe pairs info from Mercury Zephyr Programs

API should work like this

```
const { data } = await axios.get<MercuryPair[]>(`https://zephyr-programs.soroswap.finance/`, {
    params: {
    protocol: protocolName
      network: networkName,
    },
  });
  return data;
};
```

protocolName can be "phoenix", "soroswap" or "aqua"

- [x] Create API with Express
- [x] Set up Vercel.json and Set up Vercel. Use your own vercel for now
- [x] Write Vercel set up instructions in server/README.md
- [x] Move ALL Mercury calls from info to this API
- [ ] Create documentation of this API using Swagger. This documentatin should also be in Vercel. Use your own vercel for now
- [x] Create API for events like https://github.com/soroswap/info/blob/main/pages/api/events/index.tsx
- [ ] Create API for pairs like https://github.com/soroswap/info/blob/main/pages/api/pairs/plain.tsx
- [ ] (for all AMMs)
- [ ] Create API for tokens like https://github.com/soroswap/info/blob/main/pages/api/tokens/index.tsx
- [ ] After moving ALL calls to Mercury from the info repo to here, and merged PR here, with a domain... do a PR on info repo to get info from here

**Comment by Benjtalkshow** [comment]
@esteblock Can i work on this? I can handle this too.

**Comment by Amarjeet325** [comment]
Can I handle this task?

**Comment by wheval** [comment]
Hello @esteblock , can i handle this?

**Comment by Michaelkingsdev** [comment]
Let me handle this sir

**Comment by 0xdevcollins** [comment]
@esteblock I can tackle this sir

**Comment by martinvibes** [comment]
Hey @esteblock may i handle this issue?
Please kindly assign :)

**Comment by mauroepce** [comment]
Is it okay if I tackle this?

**Comment by nicopobl** [comment]
Can i tackle this one?
